version: 3

silent: true

tasks:
  e2e:
    cmd: node dist/main.js

  eslint:
    - yarn --silent lint:eslint
    - echo "eslint finished"

  build:
    cmds:
      - echo "build began"
      - yarn --silent build
      - yarn --silent add-extensions
      - task: e2e

  lint-build-watcher:
    deps: [eslint, build]
    sources: [src/**/*.ts]
    generates: [dist/**/*.js]
    method: timestamp
    # defer: [echo "--------------------"]

  lint-build-watch: task lint-build-watcher -w

  serve: yarn --silent serve

  start:
    deps: [serve, lint-build-watch]
