version: 3

silent: true

tasks:
  e2e-node:
    sources: [src/**/*.ts]
    cmds: [npm run e2e:vite-node]
  
  e2e-deno:
    sources: [src/**/*.ts]
    cmds: [deno task e2e]

  e2e-bun:
    sources: [src/**/*.ts]
    cmds: [bun run ./src/main]

  eslint-node:
    sources: [src/**/*.ts]
    cmds:
      - echo "eslint started"
      - npx tsc
      - npx eslint src
      - echo "eslint finished"

  eslint-deno:
    sources: [src/**/*.ts]
    cmds:
      - echo "eslint started"
      - deno run -A npm:typescript@*/tsc
      - deno run -A npm:eslint src
      - echo "eslint finished"

  eslint-bun:
    sources: [src/**/*.ts]
    cmds:
      - echo "eslint started"
      - bun x tsc
      - bun x eslint src
      - echo "eslint finished"

  lint-e2e-watch: task --parallel --watch eslint-bun e2e-bun

  serve-node: npx vite --port 3000 --open

  serve-deno: deno run -A npm:vite --port 3000 --open

  serve-bun: bun x --bun vite --port 3000 --open

  build-node: npx vite build

  # Terser does not seem to be able to run in Deno / 2024-10-12 
  build-deno: deno run -A npm:vite build

  build-bun: bun x --bun vite build

  start:
    deps: [serve-bun, lint-e2e-watch]
