version: 3

silent: true

tasks:
  eslint:
    - yarn --silent lint:eslint
    - echo "eslint finished"

  build:
    cmds:
      - echo "build began"
      - yarn --silent build
      - yarn --silent add-extensions

  lint-build-watcher:
    deps: [eslint, build]
    sources: [src/**/*.ts]
    generates: [dist/**/*.js]
    method: timestamp

  lint-build-watch: task lint-build-watcher -w

  serve: yarn --silent serve

  start:
    deps: [serve, lint-build-watch]
