version: 3

silent: true

tasks:
  e2e-node:
    sources: [src/**/*.ts]
    cmds: [npm run e2e:vite-node]
  
  e2e-deno:
    sources: [src/**/*.ts]
    cmds: [deno task e2e]

  eslint:
    sources: [src/**/*.ts]
    cmds:
      - echo "eslint started"
      - npx tsc
      - npx eslint src
      - echo "eslint finished"

  lint-e2e-watch: task --parallel --watch eslint e2e-deno

  serve: npm run dev

  start:
    deps: [serve, lint-e2e-watch]
