version: 3

silent: true

tasks:
  e2e:
    sources: [src/**/*.ts]
    cmds: [npx vite-node ./src/main.ts]

  eslint:
    sources: [src/**/*.ts]
    cmds:
      - echo "eslint started"
      - npx tsc
      - npx eslint --fix src
      - echo "eslint finished"

  lint-e2e-watch: task --parallel -w eslint e2e

  serve: npm run dev

  start:
    deps: [serve, lint-e2e-watch]
