version: 3

silent: true

tasks:
  zip:
    sources: [yaml/*]
    cmds: [yarn zip]

  e2e:
    deps: [zip]
    cmds: [npx vite-node ./src/main.ts]

  eslint:
    sources: [src/**/*.ts]
    cmds:
      - echo "eslint started"
      - yarn tsc
      - yarn --silent eslint --fix src
      - echo "eslint finished"

  lint-e2e-watch: task --parallel -w eslint e2e

  serve: yarn --silent dev

  start:
    deps: [serve, lint-e2e-watch]
