version: 3

silent: true

tasks:
  e2e: npx vite-node ./src/main.ts

  eslint:
    - yarn --silent eslint --fix src
    - echo "eslint finished"

  lint-e2e-watcher:
    deps: [eslint, e2e]
    sources: [src/**/*.ts]
    # generates: [dist/**/*.js]
    # method: timestamp
    # defer: [echo "--------------------"]

  lint-e2e-watch: task lint-e2e-watcher -w

  serve: yarn --silent dev

  start:
    deps: [serve, lint-e2e-watch]
