import type { IEnemyJson } from "../IEnemyJson";

/**
 * The "spawner" enemy is not a normal enemy.
 * It can do everything that an enemy can do, but it's
 * primary purpose is to auto-spawn at [0, 0] and
 * be resposible for spawning enemies.
 */
export const spawner: IEnemyJson = {
   name: "spawner",
   diameter: 20,
   hp: 9999,
   actions: [
      { type: 'wait', frames: 120 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 159 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 199 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 239 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 279 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 319 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 359 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 399 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 128.5, y: -22 } },
      { type: 'wait', frames: 1 },
      { type: 'spawn', enemy: 'nonShootingAimer', position: { x: 228.5, y: -22 } },
      { type: 'wait', frames: 559 },
      { type: 'spawn', enemy: 'sinusLeft', position: { x: 75, y: -20 } },
      { type: 'wait', frames: 71 },
      { type: 'spawn', enemy: 'sinusRight', position: { x: 280, y: -20 } },
      { type: 'wait', frames: 629 },
      { type: 'spawn', enemy: 'sinusLeft', position: { x: 75, y: -20 } },
      { type: 'wait', frames: 141 },
      { type: 'spawn', enemy: 'sinusRight', position: { x: 280, y: -20 } },
      { type: 'wait', frames: 699 },
      { type: 'spawn', enemy: 'sinusLeft', position: { x: 75, y: -20 } },
      { type: 'wait', frames: 211 },
      { type: 'spawn', enemy: 'sinusRight', position: { x: 280, y: -20 } },
      { type: 'wait', frames: 769 },
      { type: 'spawn', enemy: 'sinusLeft', position: { x: 75, y: -20 } },
      { type: 'wait', frames: 281 },
      { type: 'spawn', enemy: 'sinusRight', position: { x: 280, y: -20 } },
      { type: 'wait', frames: 839 },
      { type: 'spawn', enemy: 'sinusLeft', position: { x: 75, y: -20 } },
      { type: 'wait', frames: 351 },
      { type: 'spawn', enemy: 'sinusRight', position: { x: 280, y: -20 } },
      { type: 'wait', frames: 1089 },
      { type: 'spawn', enemy: 'firstMiniboss1', position: { x: 118.881, y: -20 } },
      { type: 'wait', frames: 351 },
      { type: 'spawn', enemy: 'firstMiniboss2', position: { x: 237.762, y: -20 } }
   ]
};
