# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: e2e-deno

on:
  push:
    branches: ["vite-master-safe-always-working-not-broken"]
  pull_request:
    branches: ["vite-master-safe-always-working-not-broken"]

permissions:
  contents: read

jobs:
  e2e-deno:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          # Targets the latest major, minor and patch version of Deno.
          deno-version: vx.x.x

      - name: Run e2e
        run: deno task e2e
